### ISSUE TITLE
Frontmatter parsing with certain characters fails

### ISSUE THREAD

**Issue by KucharczykL** [Mara-Li/mkdocs_obsidian_publish#4]
The frontmatter:
```yml
---
- name: A Christmas Carol
- dates:
  - published: 1843-12-19
  - started: 2021-02-28
  - finished: 2021-03-14
- tags: [ #source/book ]
- links: 
- people:
  - [[Charles Dickens]]
  - John Leech
- extra:
  - type: Standard Ebooks
  - genre: fiction
  - url:
    - https://standardebooks.org/ebooks/charles-dickens/a-christmas-carol
- share: true
---
```

The error:
```bash
> obs2mk --force --git
[13:19:11] STARTING CONVERT [ALL] OPTIONS :
- NO PUSH
- FORCE DELETIONS
Traceback (most recent call last):
  File "/home/lukas/.local/bin/obs2mk", line 8, in <module>
    sys.exit(main())
  File "/home/lukas/.local/lib/python3.10/site-packages/mkdocs_obsidian/__main__.py", line 139, in main
    all.convert_all(delopt, ng, stop_share, meta_update)
  File "/home/lukas/.local/lib/python3.10/site-packages/mkdocs_obsidian/common/convert_all.py", line 139, in convert_all
    new_files, clipkey = search_share(1, stop_share, meta)
  File "/home/lukas/.local/lib/python3.10/site-packages/mkdocs_obsidian/common/convert_all.py", line 65, in search_share
    yaml_front = frontmatter.load(filepath)
  File "/home/lukas/.local/lib/python3.10/site-packages/frontmatter/__init__.py", line 150, in load
    return loads(text, encoding, handler, **defaults)
  File "/home/lukas/.local/lib/python3.10/site-packages/frontmatter/__init__.py", line 165, in loads
    metadata, content = parse(text, encoding, handler, **defaults)
  File "/home/lukas/.local/lib/python3.10/site-packages/frontmatter/__init__.py", line 82, in parse
    fm = handler.load(fm)
  File "/home/lukas/.local/lib/python3.10/site-packages/frontmatter/default_handlers.py", line 238, in load
    return yaml.load(fm, **kwargs)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 707, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 725, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 774, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 851, in yaml._yaml.CParser._compose_sequence_node
  File "yaml/_yaml.pyx", line 776, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 890, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 774, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 849, in yaml._yaml.CParser._compose_sequence_node
  File "yaml/_yaml.pyx", line 905, in yaml._yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a flow node
did not find expected node content
  in "<unicode string>", line 8, column 1
```

**Comment by Mara-Li** [comment]
Your YAML is not valid :
![image](https://user-images.githubusercontent.com/30244939/149174424-b475875a-b9ec-4238-8480-a15de6497355.png)

Sometimes Obsidian accepts YAML that doesn't really work, in fact.

**Comment by KucharczykL** [comment]
Ah, that is good to know! I will make sure to use the YAML linter more liberally from now on. Thanks!
